'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuthStore } from '@/lib/auth';
import { api } from '@/lib/api';
import { Modal } from '@/components/ui/Modal';
import {
    LineChart,
    Line,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    Legend,
    ResponsiveContainer,
    AreaChart,
    Area,
    BarChart,
    Bar,
} from 'recharts';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface AnalyticsData {
    date: string;
    totalSales: number;
    totalLiters: number;
    petrol: number;
    diesel: number;
}

export default function ReportsPage() {
    const router = useRouter();
    const { user, isAuthenticated } = useAuthStore();
    const [loading, setLoading] = useState(true);
    const [reportType, setReportType] = useState<'weekly' | 'monthly'>('weekly');
    const [todayData, setTodayData] = useState<any>(null);
    const [salesData, setSalesData] = useState<any[]>([]);
    const [analyticsData, setAnalyticsData] = useState<AnalyticsData[]>([]);
    const [selectedReceipt, setSelectedReceipt] = useState<any | null>(null);

    useEffect(() => {
        if (!isAuthenticated || user?.role !== 'ADMIN') {
            router.push('/login');
            return;
        }
        loadReportData();
    }, [isAuthenticated, user, router, reportType]);

    const loadReportData = async () => {
        try {
            setLoading(true);
            const range = reportType === 'monthly' ? '30days' : '7days';
            const [stats, sales, analytics] = await Promise.all([
                api.getDashboardStats(),
                api.getTodaySales(),
                api.getAnalytics(range),
            ]);
            setTodayData(stats);
            setSalesData(sales.sales);
            setAnalyticsData(analytics);
        } catch (error) {
            console.error('Failed to load report data:', error);
        } finally {
            setLoading(false);
        }
    };

    const formatCurrency = (amount: number) => {
        return `Rs ${amount.toLocaleString('en-PK', { maximumFractionDigits: 0 })}`;
    };

    const exportToPDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.text('PSO Pump Management System', 14, 20);
        doc.setFontSize(12);
        doc.text(`Sales Report - ${new Date().toLocaleDateString()}`, 14, 30);
        doc.text(`Generated by: ${user?.fullName}`, 14, 36);

        // Summary
        doc.setFontSize(14);
        doc.text('Summary', 14, 50);
        doc.setFontSize(10);
        doc.text(`Total Sales: ${formatCurrency(todayData?.todaySales || 0)}`, 14, 58);
        doc.text(`Total Liters: ${todayData?.todayLiters?.toFixed(2)} L`, 80, 58);
        doc.text(`Transactions: ${todayData?.todayTransactions}`, 150, 58);

        // Sales Table
        const tableColumn = ["Date", "Time", "Fuel", "Liters", "Amount", "Payment"];
        const tableRows: any[] = [];

        salesData.forEach((sale) => {
            const saleData = [
                new Date(sale.saleDate).toLocaleDateString(),
                new Date(sale.saleDate).toLocaleTimeString(),
                sale.fuelType,
                sale.liters.toFixed(2),
                formatCurrency(sale.totalAmount),
                sale.paymentMethod,
            ];
            tableRows.push(saleData);
        });

        autoTable(doc, {
            head: [tableColumn],
            body: tableRows,
            startY: 70,
        });

        doc.save(`sales-report-${new Date().toISOString().split('T')[0]}.pdf`);
    };

    const generateReceipt = (sale: any) => {
        const doc = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: [80, 150] // Thermal printer size
        });

        doc.setFontSize(12);
        doc.text('PSO Station', 40, 10, { align: 'center' });
        doc.setFontSize(10);
        doc.text('Official Receipt', 40, 16, { align: 'center' });
        doc.text('--------------------------------', 40, 20, { align: 'center' });

        doc.setFontSize(9);
        let y = 30;
        doc.text(`Date: ${new Date(sale.saleDate).toLocaleString()}`, 5, y); y += 5;
        doc.text(`Sale #: ${sale.saleNumber}`, 5, y); y += 5;
        doc.text(`Operator: ${sale.operator?.fullName || 'Admin'}`, 5, y); y += 8;

        doc.text('--------------------------------', 40, y, { align: 'center' }); y += 5;

        doc.setFontSize(10);
        doc.text(`${sale.fuelType} @ ${sale.pricePerLiter}`, 5, y);
        doc.text(`${sale.liters.toFixed(2)} L`, 75, y, { align: 'right' }); y += 5;

        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text(`Total: ${formatCurrency(sale.totalAmount)}`, 75, y + 5, { align: 'right' }); y += 12;
        doc.setFont('helvetica', 'normal');

        doc.setFontSize(9);
        doc.text(`Payment: ${sale.paymentMethod}`, 5, y); y += 5;
        if (sale.vehicleNumber) {
            doc.text(`Vehicle: ${sale.vehicleNumber}`, 5, y); y += 5;
        }

        doc.text('--------------------------------', 40, y, { align: 'center' }); y += 5;
        doc.text('Thank you for fueling with us!', 40, y, { align: 'center' });

        doc.autoPrint();
        window.open(doc.output('bloburl'), '_blank');
    };

    if (loading && !todayData) {
        return (
            <div className="min-h-screen bg-[var(--surface)] flex items-center justify-center">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[var(--color-primary)]" />
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-[var(--surface)] text-[var(--text-primary)] pb-20">
            {/* Header */}
            <header className="bg-[var(--background)] border-b border-[var(--border)] sticky top-[var(--header-height)] z-30">
                <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
                    <div>
                        <h1 className="text-[var(--text-h2)] font-bold text-[var(--text-primary)]">Reports & Analytics</h1>
                        <p className="text-[var(--text-secondary)]">Comprehensive Sales Overview</p>
                    </div>
                    <div className="flex gap-3">
                        <div className="flex bg-[var(--surface)] rounded-lg p-1 border border-[var(--border)]">
                            <button
                                onClick={() => setReportType('weekly')}
                                className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${reportType === 'weekly'
                                    ? 'bg-[var(--color-primary)] text-white shadow-sm'
                                    : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
                                    }`}
                            >
                                7 Days
                            </button>
                            <button
                                onClick={() => setReportType('monthly')}
                                className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${reportType === 'monthly'
                                    ? 'bg-[var(--color-primary)] text-white shadow-sm'
                                    : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
                                    }`}
                            >
                                30 Days
                            </button>
                        </div>
                        <button
                            onClick={exportToPDF}
                            className="btn btn-primary bg-emerald-600 hover:bg-emerald-700 border-none flex items-center gap-2"
                        >
                            <span>📥</span> PDF Report
                        </button>
                    </div>
                </div>
            </header>

            <main className="max-w-7xl mx-auto px-6 py-8 space-y-6">

                {/* Analytics Charts */}
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                    {/* Sales Trend Chart */}
                    <div className="card">
                        <h3 className="text-[var(--text-h4)] font-semibold mb-6">Sales Trend (Rs)</h3>
                        <div className="h-72 w-full">
                            <ResponsiveContainer width="100%" height="100%">
                                <AreaChart data={analyticsData}>
                                    <defs>
                                        <linearGradient id="colorSales" x1="0" y1="0" x2="0" y2="1">
                                            <stop offset="5%" stopColor="var(--color-primary)" stopOpacity={0.1} />
                                            <stop offset="95%" stopColor="var(--color-primary)" stopOpacity={0} />
                                        </linearGradient>
                                    </defs>
                                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" vertical={false} />
                                    <XAxis
                                        dataKey="date"
                                        stroke="var(--text-secondary)"
                                        tickLine={false}
                                        axisLine={false}
                                        dy={10}
                                        tick={{ fontSize: 12 }}
                                    />
                                    <YAxis
                                        stroke="var(--text-secondary)"
                                        tickLine={false}
                                        axisLine={false}
                                        dx={-10}
                                        tick={{ fontSize: 12 }}
                                    />
                                    <Tooltip
                                        contentStyle={{
                                            backgroundColor: 'var(--surface)',
                                            border: '1px solid var(--border)',
                                            borderRadius: '12px',
                                            boxShadow: 'var(--shadow-lg)'
                                        }}
                                        itemStyle={{ color: 'var(--text-primary)' }}
                                        labelStyle={{ color: 'var(--text-secondary)', marginBottom: '0.5rem' }}
                                        formatter={(value: number | undefined) => [`Rs ${(value || 0).toLocaleString()}`, 'Sales']}
                                    />
                                    <Area
                                        type="monotone"
                                        dataKey="totalSales"
                                        stroke="var(--color-primary)"
                                        strokeWidth={3}
                                        fillOpacity={1}
                                        fill="url(#colorSales)"
                                    />
                                </AreaChart>
                            </ResponsiveContainer>
                        </div>
                    </div>

                    {/* Fuel Volume Chart */}
                    <div className="card">
                        <h3 className="text-[var(--text-h4)] font-semibold mb-6">Fuel Volume (Liters)</h3>
                        <div className="h-72 w-full">
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={analyticsData} barGap={8}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" vertical={false} />
                                    <XAxis
                                        dataKey="date"
                                        stroke="var(--text-secondary)"
                                        tickLine={false}
                                        axisLine={false}
                                        dy={10}
                                        tick={{ fontSize: 12 }}
                                    />
                                    <YAxis
                                        stroke="var(--text-secondary)"
                                        tickLine={false}
                                        axisLine={false}
                                        dx={-10}
                                        tick={{ fontSize: 12 }}
                                    />
                                    <Tooltip
                                        contentStyle={{
                                            backgroundColor: 'var(--surface)',
                                            border: '1px solid var(--border)',
                                            borderRadius: '12px',
                                            boxShadow: 'var(--shadow-lg)'
                                        }}
                                        cursor={{ fill: 'var(--bg-secondary)' }}
                                        itemStyle={{ color: 'var(--text-primary)' }}
                                        labelStyle={{ color: 'var(--text-secondary)', marginBottom: '0.5rem' }}
                                    />
                                    <Legend wrapperStyle={{ paddingTop: '20px' }} />
                                    <Bar dataKey="petrol" name="Petrol" fill="#EF4444" radius={[4, 4, 0, 0]} maxBarSize={40} />
                                    <Bar dataKey="diesel" name="Diesel" fill="#10B981" radius={[4, 4, 0, 0]} maxBarSize={40} />
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                    </div>
                </div>

                {/* Sales Table with Receipt Button */}
                <div className="card overflow-hidden p-0">
                    <div className="p-6 border-b border-[var(--border)] flex justify-between items-center bg-[var(--surface)]">
                        <h3 className="text-[var(--text-h4)] font-semibold">Today's Transactions</h3>
                        <span className="bg-blue-50 text-blue-700 px-3 py-1 rounded-full text-sm font-medium border border-blue-100">
                            {salesData.length} records
                        </span>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full">
                            <thead className="bg-[var(--background)] border-b border-[var(--border)]">
                                <tr>
                                    <th className="px-6 py-4 text-left text-sm font-semibold text-[var(--text-secondary)] uppercase tracking-wider">Time</th>
                                    <th className="px-6 py-4 text-left text-sm font-semibold text-[var(--text-secondary)] uppercase tracking-wider">Fuel</th>
                                    <th className="px-6 py-4 text-left text-sm font-semibold text-[var(--text-secondary)] uppercase tracking-wider">Amount</th>
                                    <th className="px-6 py-4 text-left text-sm font-semibold text-[var(--text-secondary)] uppercase tracking-wider">Payment</th>
                                    <th className="px-6 py-4 text-right text-sm font-semibold text-[var(--text-secondary)] uppercase tracking-wider">Action</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-[var(--border)] bg-[var(--surface)]">
                                {salesData.length === 0 ? (
                                    <tr>
                                        <td colSpan={5} className="px-6 py-12 text-center text-[var(--text-secondary)]">
                                            No sales recorded today
                                        </td>
                                    </tr>
                                ) : (
                                    salesData.slice(0, 50).map((sale: any) => (
                                        <tr key={sale.id} className="hover:bg-[var(--background)] transition-colors">
                                            <td className="px-6 py-4 text-sm flex flex-col">
                                                <span className="font-medium text-[var(--text-primary)]">
                                                    {new Date(sale.saleDate).toLocaleTimeString()}
                                                </span>
                                                <span className="text-xs text-[var(--text-secondary)]">
                                                    op: {sale.operator?.fullName || '-'}
                                                </span>
                                            </td>
                                            <td className="px-6 py-4 text-sm">
                                                <div className="flex items-center gap-2">
                                                    <span className={`w-2 h-2 rounded-full ${sale.fuelType === 'PETROL' ? 'bg-red-500' : 'bg-green-500'}`} />
                                                    <span className="font-medium text-[var(--text-primary)]">{sale.fuelType}</span>
                                                    <span className="text-[var(--text-secondary)] text-xs">({Number(sale.liters).toFixed(1)}L)</span>
                                                </div>
                                            </td>
                                            <td className="px-6 py-4 text-sm font-bold text-[var(--color-primary)]">
                                                {formatCurrency(Number(sale.totalAmount))}
                                            </td>
                                            <td className="px-6 py-4 text-sm">
                                                <span className={`badge ${sale.paymentMethod === 'CASH' ? 'badge-success' :
                                                    sale.paymentMethod === 'CREDIT' ? 'badge-warning' :
                                                        'badge-info'
                                                    }`}>
                                                    {sale.paymentMethod}
                                                </span>
                                            </td>
                                            <td className="px-6 py-4 text-right">
                                                <button
                                                    onClick={() => setSelectedReceipt(sale)}
                                                    className="btn btn-sm btn-ghost text-[var(--text-secondary)] hover:text-[var(--text-primary)]"
                                                    title="View Receipt"
                                                >
                                                    📄
                                                </button>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            </main>

            {/* Receipt Modal */}
            <Modal
                isOpen={!!selectedReceipt}
                onClose={() => setSelectedReceipt(null)}
                title="Transaction Receipt"
                size="sm"
            >
                {selectedReceipt && (
                    <div className="flex flex-col gap-4">
                        <div className="p-4 bg-white border border-gray-200 rounded-lg shadow-sm font-mono text-sm leading-relaxed">
                            <div className="text-center mb-4 pb-4 border-b border-dashed border-gray-300">
                                <h4 className="font-bold text-lg">Al-Rehman Filling</h4>
                                <p className="text-xs text-gray-500">PSO Station</p>
                                <p className="text-xs text-gray-500 mt-2">
                                    {new Date(selectedReceipt.saleDate).toLocaleString()}
                                </p>
                            </div>

                            <div className="space-y-2 mb-4">
                                <div className="flex justify-between">
                                    <span>Sale Number:</span>
                                    <span className="font-bold">#{selectedReceipt.saleNumber}</span>
                                </div>
                                <div className="flex justify-between">
                                    <span>Pump Operator:</span>
                                    <span>{selectedReceipt.operator?.fullName || 'Admin'}</span>
                                </div>
                            </div>

                            <div className="py-4 border-y border-dashed border-gray-300 space-y-2">
                                <div className="flex justify-between font-bold">
                                    <span>{selectedReceipt.fuelType}</span>
                                    <span>{formatCurrency(Number(selectedReceipt.totalAmount))}</span>
                                </div>
                                <div className="flex justify-between text-gray-500 text-xs">
                                    <span>Price/Liter</span>
                                    <span>Rs {selectedReceipt.pricePerLiter}</span>
                                </div>
                                <div className="flex justify-between text-gray-500 text-xs">
                                    <span>Volume</span>
                                    <span>{Number(selectedReceipt.liters).toFixed(2)} L</span>
                                </div>
                            </div>

                            <div className="mt-4 space-y-2">
                                <div className="flex justify-between font-bold text-lg pt-2 border-t border-gray-200">
                                    <span>Total</span>
                                    <span>{formatCurrency(Number(selectedReceipt.totalAmount))}</span>
                                </div>
                                <div className="flex justify-between text-xs text-gray-500">
                                    <span>Payment Method</span>
                                    <span className="font-medium">{selectedReceipt.paymentMethod}</span>
                                </div>
                                {selectedReceipt.vehicleNumber && (
                                    <div className="flex justify-between text-xs text-gray-500">
                                        <span>Vehicle No</span>
                                        <span className="font-medium">{selectedReceipt.vehicleNumber}</span>
                                    </div>
                                )}
                            </div>

                            <div className="text-center mt-6 text-xs text-gray-400">
                                Thank you for fueling with us!
                            </div>
                        </div>

                        <div className="flex justify-end gap-2 pt-2">
                            <button
                                onClick={() => setSelectedReceipt(null)}
                                className="px-4 py-2 text-sm font-medium text-gray-600 hover:bg-gray-100 rounded-lg"
                            >
                                Close
                            </button>
                            <button
                                onClick={() => generateReceipt(selectedReceipt)}
                                className="px-4 py-2 text-sm font-medium bg-blue-600 text-white hover:bg-blue-700 rounded-lg shadow-sm flex items-center gap-2"
                            >
                                <span>🖨️</span> Print
                            </button>
                        </div>
                    </div>
                )}
            </Modal>
        </div>
    );
}
